apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myapp.fullname" . }}
type: Opaque
data:
  db_name: {{ default "" .Values.secret.name | b64enc | quote }}
  db_user: {{ default "" .Values.secret.user | b64enc | quote }}
  db_password: {{ default "" .Values.secret.password | b64enc | quote }}
stringData:
  db_ep: {{ default "" .Values.secret.endpoint | quote}}